apiVersion: apps/v1
kind: Deployment
metadata:
  name: husndbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: husndbd
  template:
    metadata:
      labels:
        app: husndbd
    spec:
      containers:
      - image: okteto.dev/husndbd:latest
        name: husndbd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "939427fb-7057-4957-b040-cf24eed3ba87"
        - name: Vless_Path
          value: "/vl55d35"
        - name: Vmess_UUID
          value: "939427fb-7057-4957-b040-cf24eed3ba87"
        - name: Vmess_Path
          value: "/vm669866"
        - name: Share_Path
          value: "/v2link"
